image:
  repository: eu.gcr.io/gardener-project/gardener/gardener-extension-hyper
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1
resources: {}

controllers:
  backupbucket:
    concurrentSyncs: 5
  backupentry:
    concurrentSyncs: 5
  controlplane:
    concurrentSyncs: 5
  infrastructure:
    concurrentSyncs: 5
  worker:
    concurrentSyncs: 5
  ignoreOperationAnnotation: false

disableControllers: []
disableWebhooks: []

 imageVectorOverwrite: |
   images:
   - name: machine-controller-manager
     sourceRepository: github.com/gardener/machine-controller-manager
     repository: docker.io/guydaich/machine-controller-manager
     tag: "0.22.0-aws-encrypted-volume"
     version: 0.13.3
#   - name: pause-container
#     sourceRepository: github.com/kubernetes/kubernetes/blob/master/build/pause/Dockerfile
#     repository: gcr.io/google_containers/pause-amd64
#     tag: "3.1"
#     version: ">= 1.12"
#   ...

webhookConfig:
  serverPort: 443

config:
  clientConnection:
    acceptContentTypes: application/json
    contentType: application/json
    qps: 100
    burst: 130
  machineImages:
  - name: coreos
    version: 2135.6.0
    regions:
    - ami: ami-0b4e04c2cc22a915e
      name: eu-west-1
    - ami: ami-034fd8c3f4026eb39
      name: eu-central-1
    - ami: ami-04e51eabc8abea762
      name: us-east-1
    - ami: ami-00893b3a357694f05
      name: us-east-2
  etcd:
    storage:
      className: gardener.cloud-fast
      capacity: 80Gi
#   backup:
#     schedule: "0 */24 * * *"

gardener:
  seed:
    provider: aws
